### ISSUE TITLE
代码细节疑问

### ISSUE THREAD

**Issue by Wangpeiyi9979** [AtmaHou/FewShotTagging#19]
您好，很感谢您的工作，简单看了一下代码，关于原始论文的
![image](https://user-images.githubusercontent.com/42565075/99624650-92eefa80-2a69-11eb-9c83-f02a4a2b526e.png)
有些疑惑。

1、按TapNet中的说法，这个Φ应该是开始随机初始化的，每一个tag都对应一个向量，然后您在代码中的实现是这一行吗：
![image](https://user-images.githubusercontent.com/42565075/99624759-c893e380-2a69-11eb-86e6-923a55df5080.png)
原文采用的BIO形式的标签，那么这个矩阵的维度不该是 num_tags*2+1, bert_emb_dim?

2、关于这个Φ的作用：因为是每一个tag对应一个向量，训练集和测试集的类别不交叉，训练时只能得到训练集相关类别的φi，但是测试时对应类别的φi仍然完全是随机的呀，这个φ到底有什么用呢。

**Comment by laiyongkui1997** [comment]
Hello, the size of labels is represented by `num_tags`, which contains all number of `B-x` + `I-x` + `O`.

As you said, the label size is different between train and test, so we set a big size of anchors which is **3 times** of training label size. Because of the big size of anchors, it can work when the testing label number is bigger than the training label number. Off course you can set a bigger coefficient such as 5, 10 etc.

When using the anchors, we select some anchors from the whole set to make that each label matches an anchor.  

The meaning of the anchors is used to push away the label prototype representation in embedding space. After training, the anchors will surround the label prototypes, so as push-away anchors, it can work well in testing.

The more information refers to [TapNet](https://arxiv.org/abs/1905.06549).

**Comment by Wangpeiyi9979** [comment]
thanks for your reply

After training, we can just obtain the reasonable anchor of the train class label, because the set of train class label and test class label are disjoint,  how can we obtain the reasonable anchor of the test class label?

**Comment by AtmaHou** [comment]
> thanks for your reply
> 
> After training, we can just obtain the reasonable anchor of the train class label, because the set of train class label and test class label are disjoint, how can we obtain the reasonable anchor of the test class label?


The TapNet assumes that anchors are task-agnostic and share them across different tasks. 
In this aspect, the anchors just need to be well separated in mapped space. 
Please refer to last paragraph of Section 2.2 of [TapNet](https://arxiv.org/pdf/1905.06549.pdf).

**Comment by Wangpeiyi9979** [comment]
Got it, thx
