### ISSUE TITLE
系统找不到文件

### ISSUE THREAD

**Issue by SwaggyZhang** [AtmaHou/FewShotTagging#25]
使用Git运行时，系统找不到文件
<img width="1724" alt="运行问题" src="https://user-images.githubusercontent.com/43746996/106883406-e7298280-671a-11eb-8fec-cffe19646518.png">

**Comment by laiyongkui1997** [comment]
是不是window下的文件路径的表示不一样？

**Comment by SwaggyZhang** [comment]
> 是不是window下的文件路径的表示不一样？

貌似不是路径表示的问题。。

**Comment by AtmaHou** [comment]
(1) You can first confirm whether the data has been downloaded to the specified location.
(2) As the log shows, the error happens simply when the system wants to build a folder. 
Because this is decoupled from our code, you can try to fix it by directly building a folder from the command line and verifying what happens.

**Comment by SwaggyZhang** [comment]
> (1) You can first confirm whether the data has been downloaded to the specified location.
> (2) As the log shows, the error happens simply when the system wants to build a folder.
> Because this is decoupled from our code, you can try to fix it by directly building a folder from the command line and verifying what happens.

Since that the folder name in win10 must less than 255 characters, the program could not make the path successfully.
